### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by AlexMokin** [SlavaTel/whatsapp-ui#1]
Looks good. But too simple

Add differnt type of messages - file, image, video audio

**Comment by SlavaTel** [comment]
Hi, i don't know how to add different type of messages to my page, because my page is contact list, but i have been added search and menu icon animation, and some animation at nav menu.  

Link: https://slavatel.github.io/whatsapp-ui/  

If this is enough, I ask you to close the issue and my pull-requests for JS-assignments tasks and add me to the third task.

**Comment by AlexMokin** [comment]
I thought that was a chat. In this case implement the chat with different types of messages

**Comment by SlavaTel** [comment]
Click click on the first conversation or message icon and go to the chat page with different type of messages
![image](https://user-images.githubusercontent.com/55404308/89030144-245a2580-d330-11ea-8bd8-b4d8679201f1.png)
Click to the back icon and go to the chat list page

**Comment by ilya4321** [comment]
Thanks, look fine, thanks for the efforts. The issue can be closed
